FROM gliderlabs/alpine:3.3
VOLUME /mnt/routes
VOLUME /var/run/docker.sock:/var/run/docker.sock
EXPOSE 80

ENV GOPATH /go
RUN apk-install go git mercurial build-base gdb
RUN git clone https://github.com/gliderlabs/logspout.git /go/src/github.com/gliderlabs/logspout
COPY ./fluentd /go/src/github.com/gliderlabs/logspout/fluentd
COPY ./modules.go /go/src/github.com/gliderlabs/logspout/modules.go
WORKDIR /go/src/github.com/gliderlabs/logspout
RUN go get
CMD go get \
        && go build -ldflags "-X main.Version dev" -o /bin/logspout \
        && exec /bin/logspout